import { Injectable } from '@angular/core';
import { RealtimeDbService } from './rtdb.service'; // Assuming your RealtimeDbService is in the same directory
import { UserInfoModel } from '../models/user.model';
import { ref } from '@angular/fire/database';

@Injectable({
  providedIn: 'root',
})
export class UserDbService extends RealtimeDbService {
  constructor(private realtimeDbService: RealtimeDbService) {
    super(realtimeDbService['database']);
  }

  async createNewUser(userDataObject: UserInfoModel): Promise<string> {
    const pathOfUsersTree = '/my-users/';

    try {
      // The entryAutoId will be the key auto-generated by Firebase
      // where the new entry object (userDataObject) will be stored.
      const autoGenFirebaseKey = await this.createEntry<UserInfoModel>(
        pathOfUsersTree + '/' + userDataObject.userId,
        userDataObject,
        false, // If false no FB timestamp will be added to the userDataObject
        true // Value of useFbCustomId if true then the value of the objects root
        // will be the FB auto generated key (i.e. '-OLpCHj-Kp9MtSps2JEB')
        // but if false then id is the value of the path's last part, i.e. if
        // path is '/users/lala/user-23' then the name of the object's root
        // will be 'user-23'
      );

      ////// This section will update the userDataObject.userId with the entryAutoId
      // That way our userId will have the same unique value of the location
      //  reference it is stored in the database.
      const updatedUserData = {
        ...userDataObject,
        userId: autoGenFirebaseKey,
      };

      // Update the entry in the database with the updated data
      await this.updateEntry(
        pathOfUsersTree + '/' + autoGenFirebaseKey,
        updatedUserData
      );

      return autoGenFirebaseKey;
    } catch (error) {
      console.error('Error creating user:', error);
      throw error; // Re-throw the error to be handled by the caller
    }
  }
}
